### ISSUE TITLE
Cast errors with 0.4.0

### ISSUE THREAD

**Issue by garrensmith** [42-technology-ltd/nrfxlib#16]
Hi, I'm very new to doing embedded dev with Rust. 
I'm trying to use https://github.com/42-technology-ltd/nrf9160-demo
but I keep getting cast errors like this:
```
let result = unsafe { sys::nrf_write(self.fd, ptr as *const _, length) };
    |                                                                        ^^^^^^ expected `u32`, found `usize`
```

Is there a way to fix this or can I help fix it?

**Comment by jonathanpallant** [comment]
Which version of nrfxlib are you using with the demo crate? It should probably be updated to use the latest one.

**Comment by garrensmith** [comment]
I've tried the master branch for the `nrf9160-demo` and that doesn't build. I played around with updating dependencies which caused the above issue. I think switched to the `use_latest_nrfxlib` branch. That failed to get `nrfxlib`. I changed updated the nrfxlib to:

```
nrfxlib = {git = "https://github.com/42-technology-ltd/nrfxlib"}
```

That builds up to a point and then I get:
```
warning: Linking globals named 'DEVICE_PERIPHERALS': symbol multiply defined!

error: failed to load bc of "nrf9160_pac-149a0337cd75d160.nrf9160_pac.780wv3by-cgu.0.rcgu.o": 

error: aborting due to previous error; 1 warning emitted

error: could not compile `nrf9160-demo`.
```
Any ideas on how to fix that?

**Comment by jonathanpallant** [comment]
Please see https://github.com/42-technology-ltd/nrf9160-demo/pull/1 for a working example using nrfxlib v1.2.0.
