### ISSUE TITLE
PollEntry mutably borrows the Pollable

### ISSUE THREAD

**Issue by FrozenDroid** [42-technology-ltd/nrfxlib#4]
Great work on the library! 

One thing I was a little confused by, is the mutable borrow [here](https://github.com/42-technology-ltd/nrfxlib/blob/master/src/raw.rs#L375). I can't really find a reason why it'd have to be mutably borrowed, since it works just fine when changing it into an immutable borrow. 
The reason I had to change this was because I wanted to receive data from the socket after polling it, which was not possible because the socket was already being mutably borrowed by the PollEntry.

I'll drop a PR to change this.

**Comment by jonathanpallant** [comment]
I think the idea was to make it clear that you can't read or write while you are polling. It does mean you need to destroy the PollEntry after polling though, and see as the file handles are all just integers anyway, I agree it was probably more trouble than it was worth.
